name: "Personal Metrics"
on:
  # Schedule updates (Daily at 0600 and 1800)
  schedule: [{cron: "0 6,18 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Base_content:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: classic
          token: ${{ secrets.METRICS_TOKEN }}
          user: Robert-Kauth
          committer_gist: "Robert-Kauth/Metrics.svg"
          base: header, repositories                     # Only display "header" and "repositories" sections
          repositories: 100                              # Query only last 100 repositories
          repositories_batch: 25                         # Query repositories 25 by 25 (lower this to avoid API timeouts)
          repositories_forks: no                         # Don't include forks
          repositories_affiliations: owner, collaborator # Display only repositories where user is owner or collaborator
          repositories_skipped: Robert-Kauth/Robert-Kauth # Exclude automatically "Robert-Kauth/Robert-Kauth" repository from plugins allowing a skip list
          commits_authoring: kauthr@gmail.com     # Handle you use when authoring commits, which can be used to filter commits in other plugins
          # Output action
          output_action: "gist"
          # Output condition
          output_condition: "data-changed"
          # Retrying Rendering
          retries: 3
          retries_delay: 300
          # Configure padding
          config_padding: 0, 15 + 11%
          config_base64: yes
          # Render display width
          config_display: regular     
          # Isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          # Most used languages
          plugin_languages: yes
          plugin_languages_ignored: html, css                           # List of languages to ignore
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used
          plugin_languages_colors: "0:orange, javascript:#ff0000, ..."  # Make most used languages orange and JavaScript red
          plugin_languages_details: bytes-size, percentage              # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                                # Hides all languages less than 2%
          plugin_languages_indepth: no                                  # Get indepth stats (see documentation before enabling)
          plugin_languages_analysis_timeout: 15                         # Set maximum time for indepth analysis
          plugin_languages_categories: programming                      # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming, data # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 500                             # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 7                               # Limit recently used stats to last week
          # Topics
          plugin_topics: yes
          plugin_topics_sort: activity    # Sort by most starred topics
          plugin_topics_mode: icons    # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations
          # Coding Habits
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          config_timezone: America/Los_Angeles # Set timezone
          # WakaTime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      # Required
          plugin_wakatime_days: 7                                   # Display last week stats
          plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 4                                  # Show 4 entries per graph
          plugin_wakatime_url: https://wakatime.com                 # Wakatime url endpoint
          plugin_wakatime_user: RobKauth                            # User
          # Followup
          plugin_followup: yes
          plugin_followup_sections: repositories, user # Display overall status of issues/pull requests created on user's repositories and created by user
         
        
          

